In [175]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import re
import sys
%matplotlib tk
from mpl_toolkits.mplot3d import axes3d  # Axes3D のために必要

In [48]:
path = "/home/tokoro/Desktop/MicroBeatingRobot/MicroBeatingRobot/Databank"
files_f = glob.glob(path + "/data_displacement_f*.csv")
files_k = glob.glob(path + "/data_displacement_k*.csv")

files_f.sort()
files_k.sort()

df_f_list = []
df_k_list = []

for data_f, data_k in zip(files_f, files_k):
    df_f = pd.read_csv(data_f)
    df_k = pd.read_csv(data_k) 
    id_f = re.findall("f=.*c" ,data_f)
    id_k = re.findall("k=.*c" ,data_k)
    
    df_f = df_f.rename(columns={"displacement_x":"x_" + str(id_f[0])[0:-2],"displacement_y":"y_"+ str(id_f[0])[0:-2] })
    df_k = df_k.rename(columns={"displacement_x":"x_" + str(id_k[0])[0:-2],"displacement_y":"y_"+ str(id_k[0])[0:-2] })
    
    df_f_list.append(df_f)
    df_k_list.append(df_k)

df_f = pd.concat(df_f_list,axis = 1)
df_k = pd.concat(df_k_list,axis = 1)

df = pd.concat([df_f,df_k],axis = 1)

df = df.drop(['step', 'displacement_z'],axis = 1)
df = df.drop(index = 0)
for column_x, column_y in zip(df.filter(like = 'x_'), df.filter(like = 'y_')):
    df[column_x] -= 2
    df[column_y] += 2
    
df

,x_f=0.01,y_f=0.01,x_f=0.012,y_f=0.012,x_f=0.015,y_f=0.015,x_f=0.02,y_f=0.02,x_f=0.05,y_f=0.05,...,x_k=2.0,y_k=2.0,x_k=3.0,y_k=3.0,x_k=4.0,y_k=4.0,x_k=5.0,y_k=5.0,x_k=7.5,y_k=7.5
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,-0.002555,0.003267,-0.002129,0.002723,-0.001704,0.002178,-0.001278,0.001634,-0.000511,0.000653,...,-0.001278,0.001634,-0.001278,0.001634,-0.001278,0.001634,-0.001278,0.001634,-0.001278,0.001634
3,-0.005277,0.006626,-0.004376,0.005513,-0.003484,0.004402,-0.002600,0.003296,-0.001031,0.001314,...,-0.002574,0.003282,-0.002577,0.003284,-0.002580,0.003285,-0.002584,0.003287,-0.002592,0.003291
4,-0.008149,0.010054,-0.006732,0.008357,-0.005338,0.006666,-0.003967,0.004984,-0.001560,0.001981,...,-0.003889,0.004945,-0.003898,0.004950,-0.003908,0.004955,-0.003918,0.004960,-0.003943,0.004972
5,-0.011153,0.013528,-0.009187,0.011242,-0.007260,0.008963,-0.005376,0.006696,-0.002099,0.002656,...,-0.005222,0.006621,-0.005241,0.006631,-0.005261,0.006641,-0.005280,0.006651,-0.005328,0.006674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19996,-11.471532,-0.738152,-7.937550,-0.215913,11.336134,3.587533,16.482990,5.232389,7.652669,1.652658,...,-13.307200,-1.654490,2.835555,0.210451,9.475115,1.271998,12.602673,2.775413,15.538386,4.746238
19997,-11.471531,-0.738155,-7.937547,-0.215913,11.335956,3.590874,16.483540,5.234676,7.653010,1.653376,...,-13.308216,-1.651203,2.835514,0.213473,9.475466,1.274781,12.603010,2.778064,15.538814,4.748674
19998,-11.471530,-0.738158,-7.937544,-0.215912,11.335793,3.594244,16.484101,5.236983,7.653358,1.654102,...,-13.309212,-1.647910,2.835490,0.216507,9.475832,1.277579,12.603360,2.780732,15.539252,4.751130
19999,-11.471528,-0.738161,-7.937541,-0.215911,11.335644,3.597643,16.484672,5.239312,7.653711,1.654837,...,-13.310188,-1.644611,2.835484,0.219553,9.476213,1.280391,12.603723,2.783419,15.539701,4.753606
20000,-11.471527,-0.738163,-7.937538,-0.215910,11.335511,3.601071,16.485254,5.241663,7.654069,1.655579,...,-13.311144,-1.641308,2.835496,0.222610,9.476609,1.283219,12.604099,2.786123,15.540161,4.756102

In [134]:
df_cp = df.copy()
df.loc['mean'] = df.mean()
df_x = df.filter(like = 'x_f=')
df_y = df.filter(like = 'y_f=')
df_x = df_x.drop(columns = ['x_f=0.01','x_f=0.012'])
df_y = df_y.drop(columns = ['y_f=0.01','y_f=0.012'])

column_list_fx = df_x.columns
column_list_fy = df_y.columns

displacement_f = []

for xmean, ymean in zip(column_list_fx,column_list_fy):
    dis_mean = np.sqrt(df[xmean]['mean']**2 + df[ymean]['mean']**2)
    
    displacement_f.append(dis_mean)

In [135]:
df.loc["displacement_per_piriod"] = 0

In [136]:
for column in df.columns:
    key = 1 / float(column[4:])
    if "f=" in column:
        df[column]["displacement_per_piriod"] = df[column]["mean"] / key
    elif "k=" in column:
        df[column]["displacement_per_piriod"] = df[column]["mean"] / 50.0
    else:
        print('ERROR NOTHING COLUMN')

In [137]:
df

,x_f=0.01,y_f=0.01,x_f=0.012,y_f=0.012,x_f=0.015,y_f=0.015,x_f=0.02,y_f=0.02,x_f=0.05,y_f=0.05,...,x_k=2.0,y_k=2.0,x_k=3.0,y_k=3.0,x_k=4.0,y_k=4.0,x_k=5.0,y_k=5.0,x_k=7.5,y_k=7.5
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,-0.002555,0.003267,-0.002129,0.002723,-0.001704,0.002178,-0.001278,0.001634,-0.000511,0.000653,...,-0.001278,0.001634,-0.001278,0.001634,-0.001278,0.001634,-0.001278,0.001634,-0.001278,0.001634
3,-0.005277,0.006626,-0.004376,0.005513,-0.003484,0.004402,-0.002600,0.003296,-0.001031,0.001314,...,-0.002574,0.003282,-0.002577,0.003284,-0.002580,0.003285,-0.002584,0.003287,-0.002592,0.003291
4,-0.008149,0.010054,-0.006732,0.008357,-0.005338,0.006666,-0.003967,0.004984,-0.001560,0.001981,...,-0.003889,0.004945,-0.003898,0.004950,-0.003908,0.004955,-0.003918,0.004960,-0.003943,0.004972
5,-0.011153,0.013528,-0.009187,0.011242,-0.007260,0.008963,-0.005376,0.006696,-0.002099,0.002656,...,-0.005222,0.006621,-0.005241,0.006631,-0.005261,0.006641,-0.005280,0.006651,-0.005328,0.006674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19998,-11.471530,-0.738158,-7.937544,-0.215912,11.335793,3.594244,16.484101,5.236983,7.653358,1.654102,...,-13.309212,-1.647910,2.835490,0.216507,9.475832,1.277579,12.603360,2.780732,15.539252,4.751130
19999,-11.471528,-0.738161,-7.937541,-0.215911,11.335644,3.597643,16.484672,5.239312,7.653711,1.654837,...,-13.310188,-1.644611,2.835484,0.219553,9.476213,1.280391,12.603723,2.783419,15.539701,4.753606
20000,-11.471527,-0.738163,-7.937538,-0.215910,11.335511,3.601071,16.485254,5.241663,7.654069,1.655579,...,-13.311144,-1.641308,2.835496,0.222610,9.476609,1.283219,12.604099,2.786123,15.540161,4.756102
mean,-7.593230,1.364130,-6.922584,-1.115930,4.935459,2.024824,7.806451,2.841457,3.683530,0.934055,...,-6.167460,-0.418171,1.358133,0.454640,4.483163,0.995094,5.961434,1.679392,7.357780,2.607105
displacement_per_piriod,-0.075932,0.013641,-0.083071,-0.013391,0.074032,0.030372,0.156129,0.056829,0.184177,0.046703,...,-0.123349,-0.008363,0.027163,0.009093,0.089663,0.019902,0.119229,0.033588,0.147156,0.052142

In [138]:
df_x = df.filter(like = 'x_k=')
df_y = df.filter(like = 'y_k=')

column_list_kx = df_x.columns
column_list_ky = df_y.columns

displacement_k = []

for xmean, ymean in zip(column_list_kx,column_list_ky):
    dis_mean = np.sqrt(df[xmean]['mean']**2 + df[ymean]['mean']**2)
    
    displacement_k.append(dis_mean)

In [139]:
column_list_k = [float(k[4:]) for k in column_list_kx]
column_list_f = [float(f[4:]) for f in column_list_fx]
column_list_kx = [k[2:] for k in column_list_kx]
column_list_fx = [f[2:] for f in column_list_fx]

In [140]:
column_list_k,column_list_f

([0.1, 0.5, 1.0, 10.0, 2.0, 3.0, 4.0, 5.0, 7.5],
 [0.015, 0.02, 0.05, 0.08, 0.1, 0.15, 0.2])

In [141]:
displacement_k,displacement_f

([0.003994606676098713,
  9.813936579492625,
  4.652455678628021,
  8.307500275014455,
  6.181620544152757,
  1.4322089934894071,
  4.592271924115628,
  6.193468477260514,
  7.806018777841661],
 [5.334666260947727,
  8.307500275014455,
  3.800112272439222,
  1.9692666565598873,
  1.1571756433147906,
  0.20172318020435634,
  0.00885244768030297])

In [254]:
df_k = pd.DataFrame(data = np.array(displacement_k).reshape(1,len(displacement_k)),columns =column_list_kx)
df_k.index = ['f=0.02']
df_f = pd.DataFrame(data = np.array(displacement_f))
df_f.index = column_list_fx
df_f.columns = ['k=10.0']
df_k

,k=0.1,k=0.5,k=1.0,k=10.0,k=2.0,k=3.0,k=4.0,k=5.0,k=7.5
f=0.02,0.003995,9.813937,4.652456,8.3075,6.181621,1.432209,4.592272,6.193468,7.806019

In [255]:
df_f.index = column_list_fx
df_f.columns = ['k=10.0']
df_f = df_f.drop('f=0.02',axis = 0)

In [256]:
df_total = pd.concat([df_k,df_f],axis = 0)
df_total.index

Index(['f=0.02', 'f=0.015', 'f=0.05', 'f=0.08', 'f=0.1', 'f=0.15', 'f=0.2'], dtype='object')

In [257]:
for f in df_total.index:
    df_total.rename(index = {f:float(f[2:])}, inplace = True)
for k in df_total.columns:
    df_total.rename(columns = {k: float(k[2:])}, inplace = True)

In [251]:
df_total

,0.1,0.5,1.0,10.0,2.0,3.0,4.0,5.0,7.5
0.02,0.003995,9.813937,4.652456,8.307500,6.181621,1.432209,4.592272,6.193468,7.806019
0.015,NaN,NaN,NaN,5.334666,NaN,NaN,NaN,NaN,NaN
0.05,NaN,NaN,NaN,3.800112,NaN,NaN,NaN,NaN,NaN
0.08,NaN,NaN,NaN,1.969267,NaN,NaN,NaN,NaN,NaN
0.1,NaN,NaN,NaN,1.157176,NaN,NaN,NaN,NaN,NaN
0.15,NaN,NaN,NaN,0.201723,NaN,NaN,NaN,NaN,NaN
0.2,NaN,NaN,NaN,0.008852,NaN,NaN,NaN,NaN,NaN

## visualize

In [259]:
fig = plt.figure()
ax = fig.add_subplot(projection='3d')

columns = df_total.columns
index = df_total.index
ax.scatter(columns, index,df_total[columns][index])

KeyError: '[0.02, 0.015, 0.05, 0.08, 0.15, 0.2] not in index'

In [241]:
columns

Float64Index([0.1, 0.5, 1.0, 10.0, 2.0, 3.0, 4.0, 5.0, 7.5], dtype='float64')