In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob
import re
%matplotlib tk

In [85]:
path = "/home/tokoro/Desktop/MicroBeatingRobot/MicroBeatingRobot/Databank"
files = glob.glob(path + "/data_displacement_f*.csv")
files.sort()
df_list = []
for data in files:
    df = pd.read_csv(data)
    numid = re.findall("f=.*c" ,data)
    df = df.rename(columns={"displacement_x":"x_" + str(numid[0])[0:-2],"displacement_y":"y_"+ str(numid[0])[0:-2] })
    df_list.append(df)
df = pd.concat(df_list,axis = 1)
df = df.drop(['step', 'displacement_z'],axis = 1)
df = df.drop(index = 0)
for column_x, column_y in zip(df.filter(like = 'x_'), df.filter(like = 'y_')):
    df[column_x] -= 2
    df[column_y] += 2
df

,x_f=0.01,y_f=0.01,x_f=0.012,y_f=0.012,x_f=0.015,y_f=0.015,x_f=0.02,y_f=0.02,x_f=0.05,y_f=0.05,x_f=0.08,y_f=0.08,x_f=0.1,y_f=0.1,x_f=0.15,y_f=0.15,x_f=0.2,y_f=0.2
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,-0.002555,0.003267,-0.002129,0.002723,-0.001704,0.002178,-0.001278,0.001634,-0.000511,0.000653,-0.000319,0.000408,-0.000256,0.000327,-0.000170,0.000218,-0.000128,0.000163
3,-0.005277,0.006626,-0.004376,0.005513,-0.003484,0.004402,-0.002600,0.003296,-0.001031,0.001314,-0.000643,0.000821,-0.000514,0.000656,-0.000342,0.000437,-0.000257,0.000328
4,-0.008149,0.010054,-0.006732,0.008357,-0.005338,0.006666,-0.003967,0.004984,-0.001560,0.001981,-0.000971,0.001236,-0.000776,0.000989,-0.000516,0.000659,-0.000387,0.000494
5,-0.011153,0.013528,-0.009187,0.011242,-0.007260,0.008963,-0.005376,0.006696,-0.002099,0.002656,-0.001303,0.001656,-0.001041,0.001324,-0.000692,0.000881,-0.000518,0.000661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19996,-11.471532,-0.738152,-7.937550,-0.215913,11.336134,3.587533,16.482990,5.232389,7.652669,1.652658,4.037388,0.721109,2.579670,0.305513,0.706637,-0.164343,0.088778,-0.120318
19997,-11.471531,-0.738155,-7.937547,-0.215913,11.335956,3.590874,16.483540,5.234676,7.653010,1.653376,4.037530,0.721494,2.579789,0.305830,0.706854,-0.164093,0.088770,-0.120249
19998,-11.471530,-0.738158,-7.937544,-0.215912,11.335793,3.594244,16.484101,5.236983,7.653358,1.654102,4.037675,0.721883,2.579911,0.306150,0.707072,-0.163840,0.088761,-0.120178
19999,-11.471528,-0.738161,-7.937541,-0.215911,11.335644,3.597643,16.484672,5.239312,7.653711,1.654837,4.037824,0.722276,2.580035,0.306473,0.707291,-0.163586,0.088752,-0.120106
20000,-11.471527,-0.738163,-7.937538,-0.215910,11.335511,3.601071,16.485254,5.241663,7.654069,1.655579,4.037975,0.722672,2.580161,0.306799,0.707509,-0.163331,0.088742,-0.120033

In [86]:
df.describe()

,x_f=0.01,y_f=0.01,x_f=0.012,y_f=0.012,x_f=0.015,y_f=0.015,x_f=0.02,y_f=0.02,x_f=0.05,y_f=0.05,x_f=0.08,y_f=0.08,x_f=0.1,y_f=0.1,x_f=0.15,y_f=0.15,x_f=0.2,y_f=0.2
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,-7.593606,1.364197,-6.922926,-1.115985,4.935702,2.024923,7.806834,2.841596,3.683705,0.934099,1.932987,0.376735,1.150158,0.127724,0.195109,-0.051267,-0.006137,-0.006381
std,7.132223,5.005820,2.290792,2.226161,3.701320,1.286239,5.037417,1.610352,2.310128,0.494488,1.225987,0.229123,0.811311,0.115060,0.224783,0.076943,0.035317,0.043945
min,-14.578493,-8.715238,-8.429512,-8.193282,-1.129186,-0.655546,-0.747951,-0.101107,-0.297777,-0.003289,-0.176409,-0.009968,-0.136539,-0.064502,-0.085279,-0.183299,-0.064314,-0.122238
25%,-11.471550,-0.740168,-7.937871,-0.217929,1.649716,0.976171,3.483700,1.443713,1.681795,0.517150,0.886036,0.175446,0.434420,0.039520,0.013268,-0.112771,-0.036163,-0.035094
50%,-11.470476,-0.738161,-7.935653,-0.215834,4.905996,2.017098,7.855194,2.823519,3.679002,0.936243,1.937016,0.358923,1.141894,0.105851,0.112775,-0.055163,-0.003771,-0.004032
75%,-11.325223,-0.723615,-7.922599,-0.215210,8.155552,3.082847,12.226598,4.203026,5.673806,1.355880,2.986534,0.572316,1.856695,0.214432,0.367374,0.011406,0.017997,0.027549
max,11.723166,17.310186,0.000000,1.454604,11.688488,4.691351,16.655897,5.868364,7.669880,1.862629,4.042034,0.842391,2.580161,0.401416,0.707509,0.088232,0.088816,0.066043

In [96]:
df_cp = df.copy()
df.loc['mean'] = df.mean()
df_x = df.filter(like = 'x_f=')
df_y = df.filter(like = 'y_f=')
df_x = df_x.drop(columns = ['x_f=0.01','x_f=0.012'])
df_y = df_y.drop(columns = ['y_f=0.01','y_f=0.012'])

In [97]:
column_list_x = df_x.columns
column_list_y = df_y.columns

In [98]:
displacement = []

for xmean, ymean in zip(column_list_x,column_list_y):
    dis_mean = np.sqrt(df[xmean]['mean']**2 + df[ymean]['mean']**2)
    
    displacement.append(dis_mean)

print(displacement)

[5.334929030726053, 8.307907374618756, 3.80029279450958, 1.9693572545946854, 1.157227727113361, 0.20173176444422, 0.008852803236813835]

In [99]:
column_list_x

Index(['x_f=0.015', 'x_f=0.02', 'x_f=0.05', 'x_f=0.08', 'x_f=0.1', 'x_f=0.15',
       'x_f=0.2'],
      dtype='object')

In [100]:
f = []

for fx in column_list_x:
    value = fx[4:]
    f.append(float(value))

print(f)

[0.015, 0.02, 0.05, 0.08, 0.1, 0.15, 0.2]

In [101]:
df_mean = pd.DataFrame(f, columns = ['frec'])
df_mean['mean_displacement'] = displacement
df_mean = df_mean.sort_values('frec')
df_mean.set_index('frec', inplace = True)
df_mean

       mean_displacement
frec
0.015           5.334929
0.020           8.307907
0.050           3.800293
0.080           1.969357
0.100           1.157228
0.150           0.201732
0.200           0.008853

In [105]:
fig, ax = plt.subplots()

ax.plot(df_mean,color = "#1f77b4",zorder = 1)
ax.scatter(df_mean.index ,df_mean["mean_displacement"],color = "#ff7f0e", marker = "o", zorder = 2)
ax.set_xlabel('frec')
ax.set_ylabel('mean_displacement')
ax.grid()
plt.savefig('frec_displacement.png')
plt.show()

In [103]:
fig, ax = plt.subplots()
for x, y in zip (column_list_x,column_list_y):
    
    numid = float(x[4:])
    ax.plot(df_cp[x],df_cp[y], label = "f={}".format(numid))
    ax.set_xlabel('x_displacement')
    ax.set_ylabel('y_displacement')
    ax.set_xlim([-4,18])
    ax.set_ylim([-3,3])
    
    
    ax.legend()
    ax.set_title("MicroRobot trejectory")
    #plt.savefig('frec_all.png')
    plt.show()

In [104]:
for x, y in zip (column_list_x,column_list_y):
    fig, ax = plt.subplots()
    numid = float(x[4:])
    ax.plot(df_cp[x],df_cp[y])
    ax.set_xlabel('x_displacement')
    ax.set_ylabel('y_displacement')
    ax.set_xlim([-4,18])
    ax.set_ylim([-3,3])
    
    
    ax.set_title("MicroRobot trejectory frec = {}".format(numid))
    #plt.savefig('trajection/trajection_K={}.png'.format(numid[0]))
    plt.show()